In [2]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[4]

np.int64(15)

In [5]:
arr[1:5] #slicing

array([12, 13, 14, 15])

In [6]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[:5]

array([11, 12, 13, 14, 15])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3::2] #from 3rd index to end with 2 step

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [14]:
arr = np.arange(1,31)
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
# to get row
arr[0] # will give whole first row
arr[3]

array([16, 17, 18, 19, 20])

In [16]:
# will give a specific element
arr[0,2]

np.int64(3)

In [19]:
# slicing
""" 
i need ->
    2, 3
    7, 8
"""
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [20]:
""" 
i need ->
    19, 20
    24, 25
    29, 30
"""
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
# yess the funniest thing which was not in the game i.e., how to retrieve the cols
arr[:, 2] # : -> to get whole row right!!! nothing but a vector

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [22]:
# small array operation
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index = arr % 2 == 0
bool_index # will provide the operation which is performed as in array it is true or not

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [27]:
arr = np.arange(11,21)
bool_index = arr % 2 != 0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [28]:
arr = arr[bool_index]
arr

array([11, 13, 15, 17, 19])