In [1]:
import numpy as np

ARRAY OPERATIONS for VECTORS AND MATRIX


Arithmetic Operations

In [ ]:
a1 = np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [3]:
a2 = np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [4]:
# size of both vectors should be same
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

In [ ]:
# size of both vectors should be same
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [ ]:
# size of both vectors should be same
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [ ]:
# size of both vectors should be same
div = a1 / a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
floor = a1 // a2
floor

array([0, 0, 0, 0, 0])

In [9]:
power = a1 ** a2
power

array([      1,     128,    6561,  262144, 9765625])

In [11]:
mod = a2 % a1
mod

array([0, 1, 2, 1, 0])

Broadcasting

In [12]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr + 10

array([11, 12, 13, 14, 15])

Deep and Shallow Copy

In [17]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = arr[:5]
slice = slice * 5
slice

array([ 5, 10, 15, 20, 25])

In [ ]:
arr # arrays do not change when other change's because the address is not same - shallow copy
# if on changes of slices array parent array changes - deep copy (list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# deep copy
a = [1,2,3,4,5]
a
b = a
b[3] = 89
b
a # changed

[1, 2, 3, 89, 5]

MATRIX OPERATIONS

In [28]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [29]:
B = np.arange(5,9).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [31]:
A * B # this is simple mulitiplication element with corresponding
# but it is not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [32]:
A @ B # this is what so called matrix multiplication

array([[19, 22],
       [43, 50]])

In [33]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [34]:
# now if i want to transpose
A

array([[1, 2],
       [3, 4]])

In [35]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking Array

In [ ]:
# in stacking array we use vectors only to create matrix or vector
a = np.arange(1,5)
b = np.arange(5,9)

In [37]:
a

array([1, 2, 3, 4])

In [38]:
b

array([5, 6, 7, 8])

In [40]:
# 1. vertical stack
np.vstack((a,b)) # vertically dono arrays ko add krenge with no changes in array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# 1. horizontal stack
np.hstack((a,b)) # will come in a single vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b)) # same index will in the one row, can say a row with same index of vector input

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [43]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(c,2) # horizontally split in 2 parts

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [47]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]