In [ ]:
import numpy as np

In [ ]:
# Basic Array Creation
# in numpy arrays only one type of datatype can be stored similar to list
arr = np.array([1,2,3,4])

In [5]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [6]:
np.array(a)
# array(['1', '2', '3.5', 'hello'], dtype='<U32')

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [7]:
# whole converted into string 
# what if??
np.array([1,2,3.5])
# array([1. , 2. , 3.5])

array([1. , 2. , 3.5])

In [8]:
# 2 dimension list and arrays(numpy)
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# Array Generation Function
arr = np.arange(1,11,2) #start, stop, step
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [15]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,5,3) # linspace or linear spacing is nothing but provide us no. of elements->(3) between 1 to 5 with the same sequence
arr

array([1., 3., 5.])

In [17]:
arr = np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.random.rand(6) # provides you 6 random number between 0 and 1 (normalization)

array([0.1593532 , 0.28806636, 0.16590969, 0.74233495, 0.00987653,
       0.64159422])

In [22]:
np.random.randn(6) # provides you 6 number's between -3 to 3 (standardization)

array([-0.46875309, -0.30011368, -0.0990947 , -1.5788048 , -0.93333868,
       -0.46217152])

In [24]:
np.random.randint(10) # will provide only one number between 0 to 10
np.random.randint(10,20,5) # will provide me 5 numbers between 10 to 20 

array([15, 15, 15, 12, 10])

In [25]:
# Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.size

9

In [27]:
arr.dtype # tells you dataType

dtype('int64')

In [28]:
arr.shape # tells you dimentions (rows, cols)

(3, 3)

In [29]:
# Array Methods
arr.min()

np.int64(1)

In [30]:
arr.max()

np.int64(9)

In [31]:
arr.sum()

np.int64(45)

In [32]:
np.sum(arr, axis=0) # axis = 0 means will provide summation in column wise

array([12, 15, 18])

In [33]:
np.sum(arr, axis=1) # axis = 1 means will provide summation in row wise

array([ 6, 15, 24])

In [34]:
arr.mean()

np.float64(5.0)

In [35]:
arr.std()

np.float64(2.581988897471611)

In [36]:
arr.argmax() # provides index of highest element

np.int64(8)

In [37]:
arr.argmin() # provides index of lowest element

np.int64(0)

In [40]:
# Reshaping and Resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
# reshaping is nothing to convert the structure of array to a matrix how lets see
arr.reshape(6,5) # i have 30 elements i.e., i can convert it into 6 * 5 matrix or vice-versa

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [48]:
# Summary
# import
# np.array(input array)
# np.arange(start,stop,step) or np.arange(start,stop) or np.arange(stop)
# np.zeros(number of 1's needed) or np.zeros((rows,cols))
# np.zeros(number of 0's needed) or np.zeros((rows,cols))
# np.random.rand(number of random element) - 0 to 1
# np.random.randn(number of random element) - (-3 to 3)
# np.random.randint(stop) - will provide random number from 0 to stop - 1
# np.random.randint(start,stop) - will provide random number from start to stop - 1
# np.random.randint(start,stop,no. of elements) - will provide random number's from start to stop - 1
# arr.shape, arr.size, arr.dtype
# arr.max(), arr.min(), arr.argmax(), arr.argmin(), arr.sum(), arr.mean()
# np.sum(arr, axis= 0 or 1) 0 for col wise sum anddd and 1 for row wise sum
# arr.reshape(), arr.resize()

np.int64(30)