In [231]:
import numpy as np

Valid Sudoku

In [232]:
s = np.array([
    [ 5, 3, 4, 6, 7, 8, 9, 1, 2 ],
    [ 6, 7, 2, 1, 9, 5, 3, 4, 8 ],
    [ 1, 9, 8, 3, 4, 2, 5, 6, 7 ],

    [ 8, 5, 9, 7, 6, 1, 4, 2, 3 ],
    [ 4, 2, 6, 8, 5, 3, 7, 9, 1 ],
    [ 7, 1, 3, 9, 2, 4, 8, 5, 6 ],

    [ 9, 6, 1, 5, 3, 7, 2, 8, 4 ],
    [ 2, 8, 7, 4, 1, 9, 6, 3, 5 ],
    [ 3, 4, 5, 2, 8, 6, 1, 7, 9 ],
])

In [233]:
rowSum = np.sum(s, axis=0)
for i in rowSum:
    if i != 45:
        print("Sudoku is not valid row wise") 
        break
else:
    print("Sudoku is valid row wise") 

Sudoku is valid row wise


In [234]:
colSum = np.sum(s, axis=1)
for i in colSum:
    if i != 45:
        print("Sudoku is not valid column wise") 
        break
else:
    print("Sudoku is valid column wise") 

Sudoku is valid column wise


In [235]:
# s[0:3,0:3].sum()
# s[0:3,0:3].sum()
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(f"[{i}:{i+3}, {j}:{j+3}]")
        if s[i:i+3, j:j+3].sum() != 45:
            print("Each 3 x 3 block sum is not 45, Hence it is not valid sudoku")
            break
else:   
    print("Each 3 x 3 block sum is 45, Hence it is a valid sudoku")

    


Each 3 x 3 block sum is 45, Hence it is a valid sudoku


In [236]:
# yee zarur pdhna haii
# [age,math,science]
data = np.array([
    [18, 85, 78], # Student 1
    [19, 92, 88], # Student 2
    [17, 76, 95], # Student 3
    [18, 65, 70], # Student 4
    [20, 90, 85], # Student 5
])

In [237]:
# get the shape
data.shape

(5, 3)

In [238]:
# average age of students
# avg = np.sum(data,axis=0)[0]/len(data[:,0])
avg = np.mean(data[:,0])
print(f"in float - {avg} and in int - {int(avg)}")

in float - 18.4 and in int - 18


In [239]:
# Extract Math Marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [240]:
# find the highest science mark
data[:,2].max()

np.int64(95)

In [241]:
# get details of stuent who scored more than 90 in math
# for i in data:
#     if i[1] > 90:
#         print(i)
more_than_90 = data[:,1] > 90
newData = data[more_than_90]
newData

array([[19, 92, 88]])

In [242]:
# Increase maths mark of all student by 5
data[:,1] = data[:,1] + 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [243]:
# find how many students younger than 19
count = data[:,0] < 19
# newdata = data[count]
# newdata
data[data[:,0]<19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [244]:
# calculate avg of each subjects (column wise mean)
data[:,1:]

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [245]:
maths_marks = np.mean(data[:,1:][:,0])
maths_marks

np.float64(86.6)

In [246]:
science_marks = np.mean(data[:,2:])
science_marks

np.float64(83.2)

In [247]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [248]:
# get the student who atleast scored 80 marks in both subject
# maths more than 80
# important
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [251]:
# Replace all science marks < 75 with 0
# data[data[:, 2] < 75] = 0 ye nahi krna haii
data[:,2][data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])